---
development:
  cloud_name: <%= ENV['CLOUDIFY_NAME'] %>
  api_key: <%= ENV['CLOUDIFY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDIFY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV['CLOUDIFY_NAME'] %>
  api_key: <%= ENV['CLOUDIFY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDIFY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV['CLOUDIFY_NAME'] %>
  api_key: <%= ENV['CLOUDIFY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDIFY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false

